services:
  - type: web
    name: ems-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
